name: Gem deploy

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Tag & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag
        id: tag
        uses: forward3d/gh-gem-tag-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
      - name: Read latest Changelog entry
        id: changelog
        run: |
          echo "::set-output name=changelog::`./bin/prepare_changelog.sh`"
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish gem
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: forward3d
